name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*'
      - 'public/**/*'
      - 'vite.config.ts'
      - 'package.json'
      - 'package-lock.json'
      # exclude files and folders
      - '!**.md'
      - '!**.txt'
      - '!**.gitignore'
      - '!.github/**/*'
      - '!_local/**/*'
    tags:
      - 'v*'           # v1.0.0, v2.0.0 и т.д.
      - 'deploy'       # простой тег deploy
  workflow_dispatch:
  workflow_call:
    inputs:
      need-update:
        required: false
        type: boolean

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: "build-pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      # Skip deploy for draft commits
      - name: Check for skip deploy flag
        if: contains(github.event.head_commit.message, '[skip deploy]')
        run: |
          echo "⏭️ Skipping deploy due to [skip deploy] flag in commit message"
          exit 0
      
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v6
      
      - name: Pull latest
        if: ${{ inputs.need-update }}
        run: git pull origin main
      
      - name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: '24'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Build project
        run: npm run build
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  # Collect logs
  upload-error-logs-on-failure:
    needs: build
    uses: ./.github/workflows/upload-error-logs.yml
    with:
      artifact-name: deploy-error-logs
      log-path: |
         src/data/addresses.ts
         src/features/features.ts
