name: Change Stage

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Выберите этап'
        required: true
        default: '🛠️ In service'
        type: choice
        options:
          - '📝 Data collection'
          - '🛠️ In service'
          - '🎁 Results'
  
  workflow_call:
    inputs:
      stage:
        description: 'Этап для автоматической установки'
        required: false
        default: '🛠️ In service'
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  change-stage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      
      # Manual staging
      - name: Set stage ${{ inputs.stage }} from manual trigger
        run: |
          case "${{ inputs.stage }}" in
            '📝 Data collection')
              STAGE_NUM=1
              ;;
            '🛠️ In service')
              STAGE_NUM=2
              ;;
            '🎁 Results')
              STAGE_NUM=3
              ;;
          esac

          npm run stage -- $STAGE_NUM
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/features/features.ts
          git diff --staged --quiet || git commit -m "chore: set stage to ${{ inputs.stage }} [skip ci]"
          git push
      
      # Build up
      #- name: Build and Deploy
      #  uses: ./.github/workflows/build-and-deploy.yml

      # Collect logs
      #- name: Upload error logs on failure
      #  uses: ./.github/workflows/upload-error-logs.yml
      #  with:
      #    artifact-name: change-stage-error-logs
      #    log-path: |
      #      src/features/features.ts
